# Generated by Django 3.0.5 on 2020-04-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryptedfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedfile',
            name='file_key',
            field=models.BinaryField(max_length=255),
        ),
    ]
